import React, { createContext, useContext, useState } from "react";

type TranslationKey = string;

const translations: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    search: "Search",
    history: "History",
    library: "Library",
    profile: "Profile",
    Home: "Home",
    StudyScan: "StudyScan",
    "Saved Vault": "Saved Vault",
    Timetable: "Timetable",
    "Profile Stats": "Profile Stats",
    "Voice Space": "Voice Space",
    "Good morning": "Good morning",
    "Good afternoon": "Good afternoon",
    "Good evening": "Good evening",
    Streak: "Streak",
    Concepts: "Concepts",
    Quizzes: "Quizzes",
    Minutes: "Minutes",
    Level: "Level",
    XP: "XP",
    "weekly goal": "weekly goal",
    "Choose Tutor Persona": "Choose Tutor Persona",
    "Ask AI Teacher": "Ask AI Teacher",
    "Practice STEM Quiz": "Practice STEM Quiz",
    "Saved Concepts": "Saved Concepts",
    "Edit Profile": "Edit Profile",
    "Save Settings": "Save Settings",
    "Guest Explorer": "Guest Explorer",
    "Class 8": "Class 8",
    "Class 9": "Class 9",
    "Class 10": "Class 10",
    "Class 11": "Class 11",
    "Class 12": "Class 12",
    "Undergrad": "Undergrad",
    "Principal Study Systems": "Principal Study Systems",
    "Start Fresh": "Start Fresh",
    "Instant voice/chat doubts solver & simulation explorer": "Instant voice/chat doubts solver & simulation explorer",
    "Quick Quiz": "Quick Quiz",
    "Custom topic MCQ generator & diagnostic reward leveler": "Custom topic MCQ generator & diagnostic reward leveler",
    "Voice Tutor": "Voice Tutor",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "Listen & talk to Mascot summaries, flashcards & fun tips",
    "Scan Textbook": "Scan Textbook",
    "Click to launch the live camera instantly to analyze chapters": "Click to launch the live camera instantly to analyze chapters",
    "StudyScan Hub": "StudyScan Hub",
    "Your Offline Study Vault": "Your Offline Study Vault",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!",
    "Search offline vault contents...": "Search offline vault contents...",
    "Study Planner Timetable": "Study Planner Timetable",
    "Manage your week": "Manage your week",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.",
    "App Language": "App Language",
    "Advanced Voice Speech Narration": "Advanced Voice Speech Narration",
    "Speaking Speed": "Speaking Speed",
    "Study Career Progression Path": "Study Career Progression Path",
    "Track your academic level and rank milestones": "Track your academic level and rank milestones",
    "Your Current Level": "Your Current Level",
    "Experience Points": "Experience Points",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!",
    "Your Active Learning Progress": "Your Active Learning Progress",
    "Recent Interactive Chat Sessions": "Recent Interactive Chat Sessions",
    "Capture Physics, Chemistry, Biology, or Mathematics textbook materials directly using your device's live camera, or upload a document file to begin your immersive interactive session.": "Capture Physics, Chemistry, Biology, or Mathematics textbook materials directly using your device's live camera, or upload a document file to begin your immersive interactive session."
  },
  hi: {
    "home": "मुख्य पृष्ठ",
    "search": "खोजें",
    "history": "इतिहास",
    "library": "पुस्तकालय",
    "profile": "प्रोफ़ाइल",
    "Home": "मुख्य पृष्ठ",
    "StudyScan": "स्टडी स्कैन",
    "Saved Vault": "सुरक्षित तिजोरी",
    "Timetable": "समय-सारणी",
    "Profile Stats": "प्रोफ़ाइल सांख्यिकी",
    "Voice Space": "आवाज केंद्र",
    "Good morning": "सुप्रभात",
    "Good afternoon": "शुभ दोपहर",
    "Good evening": "शुभ संध्या",
    "Streak": "दैनिक स्ट्रीक",
    "Concepts": "अवधारणाएँ",
    "Quizzes": "क्विज़",
    "Minutes": "अभ्यास मिनट",
    "Level": "स्तर",
    "XP": "अनुभव अंक",
    "weekly goal": "साक लक्ष्य",
    "Choose Tutor Persona": "ट्यूटर शैली चुनें",
    "Ask AI Teacher": "AI शिक्षक से पूछें",
    "Practice STEM Quiz": "STEM क्विज़ अभ्यास",
    "Saved Concepts": "सुरक्षित अवधारणाएँ",
    "Edit Profile": "प्रोफ़ाइल संपादित करें",
    "Save Settings": "सेटिंग्स सहेजें",
    "Guest Explorer": "अतिथि अन्वेषक",
    "Class 8": "कक्षा 8",
    "Class 9": "कक्षा 9",
    "Class 10": "कक्षा 10",
    "Class 11": "कक्षा 11",
    "Class 12": "कक्षा 12",
    "Undergrad": "स्नातक",
    "Principal Study Systems": "मुख्य अध्ययन प्रणालियाँ",
    "Start Fresh": "नया शुरू करें",
    "Instant voice/chat doubts solver & simulation explorer": "तत्काल आवाज/चैट संदेह समाधान और सिमुलेशन एक्सप्लोरर",
    "Quick Quiz": "त्वरित प्रश्नोत्तरी",
    "Custom topic MCQ generator & diagnostic reward leveler": "कस्टम विषय MCQ जनरेटर और नैदानिक इनाम स्तर",
    "Voice Tutor": "आवाज ट्यूटर",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "शुभंकर सारांश, फ्लैशकार्ड और मजेदार टिप्स सुनें और बात करें",
    "Scan Textbook": "पाठ्यपुस्तक स्कैन करें",
    "Click to launch the live camera instantly to analyze chapters": "अध्यायों का विश्लेषण करने के लिए तुरंत लाइव कैमरा शुरू करने के लिए क्लिक करें",
    "StudyScan Hub": "स्टडीस्कैन हब",
    "Your Offline Study Vault": "आपकी ऑफ़लाइन अध्ययन तिजोरी",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "सभी सहेजे गए वैचारिक नोट्स, स्पष्टीकरण, अनुकूलित प्रश्नोत्तरी परिणाम, व्हाइटबोर्ड डूडल और वॉयस रिकॉर्डिंग स्थानीय रूप से यहां संग्रहीत हैं। इंटरनेट के बिना पढ़ें और अभ्यास करें!",
    "Search offline vault contents...": "ऑफ़लाइन तिजोरी की सामग्री खोजें...",
    "Study Planner Timetable": "अध्ययन योजनाकार समय-सारणी",
    "Manage your week": "अपने सप्ताह का प्रबंधन करें",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "विद्या को आपकी पाठ्य सांख्यिकी, कक्षा के विषयों और अभ्यास प्रश्नों की जांच करने दें ताकि 5 सर्वोत्तम साप्ताहिक अध्ययन योजनाएं बनाई जा सकें। नीचे क्लिक करके तुरंत सुझाव देखें।",
    "App Language": "ऐप भाषा",
    "Advanced Voice Speech Narration": "उन्नत आवाज भाषण वर्णन",
    "Speaking Speed": "बोलने की गति",
    "Study Career Progression Path": "अध्ययन कैरियर प्रगति पथ",
    "Track your academic level and rank milestones": "अपने शैक्षणिक स्तर और रैंक के मील के पत्थर को ट्रैक करें",
    "Your Current Level": "आपका वर्तमान स्तर",
    "Experience Points": "अनुभव अंक",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM अवधारणाओं में महारत हासिल करके, त्वरित क्विज़ में खुद को चुनौती देकर, और AI शिक्षक साथी के साथ बातचीत करके गतिशील रूप से स्तर उन्नति की स्थिति प्राप्त करें!",
    "Your Active Learning Progress": "आपकी सक्रिय सीखने की प्रगति",
    "Recent Interactive Chat Sessions": "हाल के इंटरैक्टिव चैट सत्र",
    "Capture Physics, Chemistry, Biology, or Mathematics textbook materials directly using your device's live camera, or upload a document file to begin your immersive interactive session.": "अपने डिवाइस के लाइव कैमरे का उपयोग करके सीधे भौतिकी, रसायन विज्ञान, जीव विज्ञान, या गणित पाठ्यपुस्तक सामग्री कैप्चर करें, या अपना इमर्सिव इंटरैक्टिव सत्र शुरू करने के लिए एक दस्तावेज़ फ़ाइल अपलोड करें।"
  },
  te: {
    "home": "హోమ్",
    "search": "శోధన",
    "history": "చరిత్ర",
    "library": "లైబ్రరీ",
    "profile": "ప్రొఫైల్",
    "Home": "హోమ్",
    "StudyScan": "స్టడీ స్కాన్",
    "Saved Vault": "సేవ్ చేసిన వాల్ట్",
    "Timetable": "టైమ్‌టేబుల్",
    "Profile Stats": "ప్రొఫైల్ గణాంకాలు",
    "Voice Space": "వాయిస్ స్పేస్",
    "Good morning": "శుభోదయం",
    "Good afternoon": "శుభ మధ్యాహ్నం",
    "Good evening": "శుభ సాయంత్రం",
    "Streak": "స్ట్రీక్",
    "Concepts": "భావనలు",
    "Quizzes": "ക്വിജ്లు",
    "Minutes": "ನಿಮಿಷಗಳು",
    "Level": "స్థాయి",
    "XP": "లాభం (XP)",
    "weekly goal": "వారపు लक्ष्यం",
    "Choose Tutor Persona": "ట్యూటర్ శाइల్ ని ఎంచుకోండి",
    "Ask AI Teacher": "AI టీచర్‌ని అడగండి",
    "Practice STEM Quiz": "STEM క్విజ్ ప్రాక్టీస్",
    "Saved Concepts": "సేవ్ చేసిన కాన్సెప్ట్‌లు",
    "Edit Profile": "ప్రొఫైల్‌ను సవరించండి",
    "Save Settings": "సెట్టింగ్‌లను సేవ్ చేయి",
    "Guest Explorer": "అతిథి అన్వేషకుడు",
    "Class 8": "ಕ್ಲಾಸ್ 8",
    "Class 9": "ಕ್ಲಾಸ್ 9",
    "Class 10": "ಕ್ಲಾಸ್ 10",
    "Class 11": "ಕ್ಲಾಸ್ 11",
    "Class 12": "ಕ್ಲಾಸ್ 12",
    "Undergrad": "డిగ్రీ",
    "Principal Study Systems": "ప్రధాన అధ్యయన వ్యవస్థలు",
    "Start Fresh": "మళ్లీ ప్రారంభించండి",
    "Instant voice/chat doubts solver & simulation explorer": "తక్షణ వాయిస్/చాట్ సందేహాల పరిష్కారం & సిమ్యులేషన్ ఎక్స్‌ప్లోరర్",
    "Quick Quiz": "త్వరిత క్విజ్",
    "Custom topic MCQ generator & diagnostic reward leveler": "అనుకూల టాపిక్ MCQ జెనరేటర్ & డయాగ్నస్టిక్ రివార్డ్ లెవలర్",
    "Voice Tutor": "వాయిస్ ట్యూటర్",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "మస్కట్ సారాంశాలు, ఫ్లాష్‌కార్డ్‌లు & సరదా చిట్కాలను వినండి & మాట్లాడండి",
    "Scan Textbook": "టెక్స్ట్‌బుక్ స్కాన్ చేయండి",
    "Click to launch the live camera instantly to analyze chapters": "అధ్యాయాలను విశ్లేషించడానికి తక్షణమే ప్రత్యక్ష కెమెరాను ప్రారంభించడానికి క్లిక్ చేయండి",
    "StudyScan Hub": "స్టడీస్కాన్ హబ్",
    "Your Offline Study Vault": "మీ ఆఫ్లైన్ స్టడీ వాల్ట్",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "సేవ్ చేయబడిన అన్ని కాన్సెప్ట్ నోట్స్, వివరణలు, అనుకూలీకరించిన క్విజ్ ఫలితాలు, వైట్‌బోర్డ్ డూడుల్స్ మరియు వాయిస్ రికార్డింగ్‌లు ఇక్కడ లోకల్‌గా భద్రపరచబడతాయి. ఇంటర్నెట్ లేకుండా చదవండి మరియు ప్రాక్టీస్ చేయండి!",
    "Search offline vault contents...": "ఆఫ్‌లైన్ వాల్ట్ కంటెంట్‌లను శోధించండి...",
    "Study Planner Timetable": "స్టడీ ప్లానర్ టైమ్‌టేబుల్",
    "Manage your week": "మీ వారాన్ని నిర్వహించండి",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "5 సరైన వారపు అధ్యయన ప్రణాళికలను రూపొందించడానికి విద్యా మీ పాఠాల గణాంకాలు, తరగతి అంశాలు మరియు ప్రాక్టీస్ ప్రశ్నలను పరిశీలించనివ్వండి. క్రింది క్లిక్ చేయడం ద్వారా సూచనలను తక్షణమే చూడండి.",
    "App Language": "యాప్ భాష",
    "Advanced Voice Speech Narration": "అధునాతన వాయిస్ స్పీచ్ నరేషన్",
    "Speaking Speed": "మాట్లాడే వేగం",
    "Study Career Progression Path": "స్టడీ కెరీర్ పురోగతి మార్గం",
    "Track your academic level and rank milestones": "మీ విద్యా స్థాయి మరియు ర్యాంక్ మైలురాళ్లను ట్రాక్ చేయండి",
    "Your Current Level": "మీ ప్రస్తుత స్థాయి",
    "Experience Points": "అనుభవ పాయింట్లు",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM కాన్సెప్ట్‌లలో నైపుణ్యం సాధించడం ద్వారా, శీఘ్ర క్విజ్‌లలో మిమ్మల్ని మీరు సవాలు చేసుకోవడం ద్వారా మరియు AI టీచర్ సహచరుడితో పరస్పర చర్య చేయడం ద్వారా డైనమిక్‌గా స్థాయి పురోగతి స్థితిని పొందండి!",
    "Your Active Learning Progress": "మీ క్రియాశీల అభ్యాస పురోగతి",
    "Recent Interactive Chat Sessions": "ಇತ್ತೀಚಿನ ಇಂಟರಾಕ್ಟಿವ್ ಚಾಟ್ ಸೆಷನ್‌ಗಳು",
    "Capture Physics, Chemistry, Biology, or Mathematics textbook materials directly using your device's live camera, or upload a document file to begin your immersive interactive session.": "మీ పరికరం యొక్క ప్రత్యక్ష కెమెరాను ఉపయోగించి నేరుగా ఫిజిక్స్, కెమిస్ట్రీ, బయాలజీ లేదా మ్యాథమెటిక్స్ పాఠ్యपुస్తక విషయాలను క్యాప్చర్ చేయండి లేదా మీ ఇంటరాక్టివ్ సెషన్‌ను ప్రారంభించడానికి పత్రాన్ని అప్‌లోడ్ చేయండి."
  },
  mr: {
    "home": "मुख्य पृष्ठ",
    "search": "शोध",
    "history": "इतिहास",
    "library": "पुस्तकालय",
    "profile": "प्रोफाइल",
    "Home": "मुख्य पृष्ठ",
    "StudyScan": "अभ्यास स्कॅन",
    "Saved Vault": "जतन केलेली तिजोरी",
    "Timetable": "वेळापत्रक",
    "Profile Stats": "प्रोफाइल आकडेवारी",
    "Voice Space": "आवाज केंद्र",
    "Good morning": "शुभ प्रभात",
    "Good afternoon": "शुभ दुपार",
    "Good evening": "शुभ संध्याकाळ",
    "Streak": "स्ट्रीक",
    "Concepts": "संकल्पना",
    "Quizzes": "क्विज",
    "Minutes": "मिनिटे",
    "Level": "पातळी",
    "XP": "अनुभव गुण (XP)",
    "weekly goal": "साप्ताहिक ध्येय",
    "Choose Tutor Persona": "ट्यूटर शैली निवडा",
    "Ask AI Teacher": "AI शिक्षकाला विचारा",
    "Practice STEM Quiz": "STEM क्विज सराव",
    "Saved Concepts": "जतन केलेल्या संकल्पना",
    "Edit Profile": "प्रोफाइल संपादित करा",
    "Save Settings": "सेटिंग्ज जतन करा",
    "Guest Explorer": "अतिथी शोधक",
    "Class 8": "इयत्ता ८ वी",
    "Class 9": "इयत्ता ९ वी",
    "Class 10": "इयत्ता १० वी",
    "Class 11": "इयत्ता ११ वी",
    "Class 12": "इयत्ता १२ वी",
    "Undergrad": "पदवीधर",
    "Principal Study Systems": "मुख्य अभ्यास प्रणाली",
    "Start Fresh": "नवीन सुरुवात करा",
    "Instant voice/chat doubts solver & simulation explorer": "तात्कालिक आवाज/चॅट शंका निवारक आणि सिम्युलेशन एक्सप्लोरर",
    "Quick Quiz": "त्वरित क्विझ",
    "Custom topic MCQ generator & diagnostic reward leveler": "सानुकूल विषय MCQ निर्माता आणि बक्षीस पातळी",
    "Voice Tutor": "व्हॉइस ट्यूटर",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "मॅस्कॉटचे सारांश, फ्लॅशकार्ड आणि मनोरंजक टिप्स ऐका आणि संवाद साधा",
    "Scan Textbook": "पाठ्यापुस्तक स्कॅन करा",
    "Click to launch the live camera instantly to analyze chapters": "धडे अभ्यासण्यासाठी त्वरित थेट कॅमेरा सुरू करा",
    "StudyScan Hub": "अभ्यास स्कॅन हब",
    "Your Offline Study Vault": "तुमची ऑफलाइन अभ्यास तिजोरी",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "सर्व जतन केलेल्या संकल्पना नोट्स, स्पष्टीकरण, सानुकूलित क्विझ निकाल, व्हाईटबोर्ड डूडल आणि व्हॉइस रेकॉर्डिंग येथे स्थानिक पातळीवर संग्रहित केले जातात. इंटरनेटशिवाय वाचा आणि सराव करा!",
    "Search offline vault contents...": "ऑफलाइन तिजोरीमधील सामग्री शोधा...",
    "Study Planner Timetable": "अभ्यास नियोजक वेळापत्रक",
    "Manage your week": "तुमच्या आठवड्याचे नियोजन करा",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "५ सर्वोत्तम साप्ताहिक अभ्यास आराखडे तयार करण्यासाठी विद्याला तुमच्या पाठाची आकडेवारी, वर्ग विषय आणि सराव प्रश्नांचे परीक्षण करू द्या. खाली क्लिक करून त्वरित सूचना पहा.",
    "App Language": "अॅपची भाषा",
    "Advanced Voice Speech Narration": "प्रगत आवाज आणि भाषण",
    "Speaking Speed": "बोलण्याचा वेग",
    "Study Career Progression Path": "अभ्यास करिअर प्रगती पथ",
    "Track your academic level and rank milestones": "तुमची शैक्षणिक पातळी आणि मैलाचे दगड ट्रॅक करा",
    "Your Current Level": "तुमची सध्याची पातळी",
    "Experience Points": "अनुभव गुण",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM संकल्पनांवर प्रभुत्व मिळवून, त्वरित क्विझमध्ये स्वतःला आव्हान देऊन आणि AI शिक्षक सोबत्याशी संवाद साधून पातळी वाढवा!",
    "Your Active Learning Progress": "तुमची सक्रिय शिक्षण प्रगती",
    "Recent Interactive Chat Sessions": "अलीकडील परस्पर चॅट सत्र"
  },
  ta: {
    "home": "முகப்பு",
    "search": "தேடல்",
    "history": "வரலாறு",
    "library": "நூலகம்",
    "profile": "சுயவிவரம்",
    "Good morning": "காலை வணக்கம்",
    "Good afternoon": "மதிய வணக்கம்",
    "Good evening": "மாலை வணக்கம்",
    "Streak": "தொடர்",
    "Concepts": "கருத்துகள்",
    "Quizzes": "வினாடி வினாக்கள்",
    "Minutes": "நிமிடங்கள்",
    Home: "முகப்பு",
    StudyScan: "ஸ்டடி ஸ்கேன்",
    "Saved Vault": "சேமிப்பகம்",
    Timetable: "கால அட்டவணை",
    "Profile Stats": "சுயவிவர புள்ளிவிவரங்கள்",
    "Voice Space": "குரல் தளம்",
    Level: "நிலை",
    XP: "அனுபவ புள்ளிகள் (XP)",
    "weekly goal": "வாராந்திர இலக்கு",
    "Choose Tutor Persona": "ஆசிரியர் பாத்திரத்தை தேர்வு செய்",
    "Ask AI Teacher": "AI ஆசிரியரிடம் கேளுங்கள்",
    "Practice STEM Quiz": "STEM வினாடி வினா பயிற்சி",
    "Saved Concepts": "சேமித்த கருத்துக்கள்",
    "Edit Profile": "சுயவிவரத்தை திருத்து",
    "Save Settings": "அமைப்புகளை சேமி",
    "Guest Explorer": "விருந்தினர் ஆய்வாளர்",
    "Class 8": "வகுப்பு 8",
    "Class 9": "வகுப்பு 9",
    "Class 10": "வகுப்பு 10",
    "Class 11": "வகுப்பு 11",
    "Class 12": "வகுப்பு 12",
    "Undergrad": "இளங்கலை",
    "Principal Study Systems": "முதன்மை கல்வி முறைகள்",
    "Start Fresh": "புதிதாகத் தொடங்கு",
    "Instant voice/chat doubts solver & simulation explorer": "உடனடி குரல்/அரட்டை சந்தேகங்கள் தீர்வு மற்றும் உருவகப்படுத்துதல்",
    "Quick Quiz": "விரைவான வினாடி வினா",
    "Custom topic MCQ generator & diagnostic reward leveler": "விருப்ப தலைப்பு MCQ ஜெனரேட்டர் & வெகுமதி நிலை",
    "Voice Tutor": "குரல் ஆசிரியர்",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "சுருக்கங்கள், அட்டைக்குறிகள் & உதவிக்குறிப்புகளைக் கேளுங்கள் & பேசுங்கள்",
    "Scan Textbook": "பாடப்புத்தகத்தை ஸ்கேன் செய்",
    "Click to launch the live camera instantly to analyze chapters": "நேரடி கேமராவைத் தொடங்கி பாடங்களை ஆய்வு செய்ய கிளிக் செய்யவும்",
    "StudyScan Hub": "ஸ்டடிஸ்கேன் மையம்",
    "Your Offline Study Vault": "ஆஃப்லைன் கல்வி பெட்டகம்",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "சேமிக்கப்பட்ட அனைத்து கருத்துக்கள், விளக்கங்கள், வினாடி வினா முடிவுகள் மற்றும் குரல் பதிவுகள் இங்கு சேமிக்கப்படும். இணையம் இல்லாமல் படிக்கவும்!",
    "Search offline vault contents...": "ஆஃப்லைன் பெட்டகத்தில் தேடு...",
    "Study Planner Timetable": "கால அட்டவணை திட்டமிடுபவர்",
    "Manage your week": "வாரத்தை நிர்வகிக்கவும்",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "வாரம் 5 சிறந்த கல்வி திட்டங்களை வகுக்க வித்யா உங்கள் பாடம் மற்றும் பயிற்சி கேள்விகளை ஆய்வு செய்யட்டும். கீழே கிளிக் செய்து பரிந்துரைகளைக் காண்க.",
    "App Language": "செயلي மொழி",
    "Advanced Voice Speech Narration": "மேம்பட்ட குரல் விவரணை",
    "Speaking Speed": "பேச்சு வேகம்",
    "Study Career Progression Path": "கல்வி முன்னேற்றப் பாதை",
    "Track your academic level and rank milestones": "உங்கள் கல்வி நிலை மற்றும் இலக்குகளை கண்காணிக்கவும்",
    "Your Current Level": "தற்போதைய நிலை",
    "Experience Points": "அனுபவ புள்ளிகள்",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM கருத்துக்களைக் கற்றுக்கொண்டு, வினாடி வினாக்கள் மற்றும் AI உடன் உரையாடி நிலைகளை உயர்த்துங்கள்!",
    "Your Active Learning Progress": "செயலில் உள்ள கற்றல் முன்னேற்றம்",
    "Recent Interactive Chat Sessions": "சமீபத்திய உரையாடல் அமர்வுகள்"
  },
  kn: {
    "home": "ಮುಖಪುಟ",
    "search": "ಹುಡುಕಾಟ",
    "history": "ಇತಿಹಾಸ",
    "library": "ಗ್ರಂಥಾಲಯ",
    "profile": "ಪ್ರೊಫೈಲ್",
    "Good morning": "ಶುಭೋದಯ",
    "Good afternoon": "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    "Good evening": "ಶುಭ ಸಂಜೆ",
    "Streak": "ಸರಣಿ",
    "Concepts": "ಪರಿಕಲ್ಪನೆಗಳು",
    "Quizzes": "ರಸಪ್ರಶ್ನೆಗಳು",
    "Minutes": "ನಿಮಿಷಗಳು",
    Home: "ಮುಖಪುಟ",
    StudyScan: "ಸ್ಟಡಿ ಸ್ಕ್ಯಾನ್",
    "Saved Vault": "ಉಳಿಸಿದ ವಾಲ್ಟ್",
    Timetable: "ವೇಳಾಪಟ್ಟಿ",
    "Profile Stats": "ಪ್ರೊಫೈಲ್ ಅಂಕಿಅಂಶಗಳು",
    Level: "ಮಟ್ಟ",
    XP: "ಅನುಭವ ಅಂಕಗಳು (XP)",
    "weekly goal": "ವಾರದ ಗುರಿ",
    "Choose Tutor Persona": "ಟ್ಯೂಟರ್ ಶೈಲಿ ಆಯ್ಕೆ ಮಾಡಿ",
    "Ask AI Teacher": "AI ಶಿಕ್ಷಕರನ್ನು ಕೇಳಿ",
    "Practice STEM Quiz": "STEM ರಸಪ್ರಶ್ನೆ ಅಭ್ಯಾಸ",
    "Saved Concepts": "ಉಳಿಸಿದ ಪರಿಕಲ್ಪನೆಗಳು",
    "Edit Profile": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    "Save Settings": "ಸೆಟ್ಟಿಂಗ್ಸ್ ಉಳಿಸಿ",
    "Guest Explorer": "ಅತಿಥಿ ಅನ್ವೇಷಕ",
    "Class 8": "ತರಗತಿ 8",
    "Class 9": "ತರಗತಿ 9",
    "Class 10": "ತರಗತಿ 10",
    "Class 11": "ತರಗತಿ 11",
    "Class 12": "ತರಗತಿ 12",
    "Undergrad": "ಪದವಿ",
    "Principal Study Systems": "ಮುಖ್ಯ ಕಲಿಕಾ ವ್ಯವಸ್ಥೆಗಳು",
    "Start Fresh": "ಹೊಸದಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    "Instant voice/chat doubts solver & simulation explorer": "ತ್ವರಿತ ಧ್ವನಿ/ಚಾಟ್ ಸಂದೇಹ ಪರಿಹಾರ ಮತ್ತು ಸಿಮ್ಯುಲೇಶನ್",
    "Quick Quiz": "ತ್ವರಿತ ರಸಪ್ರಶ್ನೆ",
    "Custom topic MCQ generator & diagnostic reward leveler": "ವಿಷಯಾಧಾರಿತ MCQ ಜನರೇಟರ್ & ಬಹುಮಾನ ಮಟ್ಟ",
    "Voice Tutor": "ಧ್ವನಿ ಬೋಧಕ",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "ಸಾರಾಂಶಗಳು, ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್‌ಗಳು ಮತ್ತು ಸಲಹೆಗಳನ್ನು ಆಲಿಸಿ & ಸಂಭಾಷಿಸಿ",
    "Scan Textbook": "ಪಠ್ಯಪುಸ್ತಕ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    "Click to launch the live camera instantly to analyze chapters": "ಅಧ್ಯಾಯಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲು ತಕ್ಷಣವೇ ಲೈವ್ ಕ್ಯಾಮೆರಾ ಚಾಲನೆಗೊಳಿಸಿ",
    "StudyScan Hub": "ಸ್ಟಡಿ ಸ್ಕ್ಯಾನ್ ಹಬ್",
    "Your Offline Study Vault": "ನಿಮ್ಮ ಆಫ್‌ಲೈನ್ ಸ್ಟಡಿ ವಾಲ್ಟ್",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "ಉಳಿಸಿದ ಎಲ್ಲಾ ಟಿಪ್ಪಣಿಗಳು, ವಿವರಣೆಗಳು, ರಸಪ್ರಶ್ನೆ ಫಲಿತಾಂಶಗಳು ಇಲ್ಲಿ ಸಂಗ್ರಹವಾಗಿರುತ್ತವೆ. ಇಂಟರ್ನೆಟ್ ಇಲ್ಲದೆ ಓದಿರಿ!",
    "Search offline vault contents...": "ಆಫ್‌ಲೈನ್ ವಾಲ್ಟ್ ವಿಷಯಗಳನ್ನು ಹುಡುಕಿ...",
    "Study Planner Timetable": "ಸ್ಟಡಿ ಪ್ಲಾನರ್ ವೇಳಾಪಟ್ಟಿ",
    "Manage your week": "ನಿಮ್ಮ ವಾರವನ್ನು ನಿರ್ವಹಿಸಿ",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "ವಿದ್ಯಾ ನಿಮ್ಮ ಪಾಠಗಳು ಮತ್ತು ಪ್ರಶ್ನೆಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ 5 ಉತ್ತಮ ಸಾಪ್ತಾಹಿಕ ಅಧ್ಯಯನ ಯೋಜನೆಗಳನ್ನು ರೂಪಿಸಲಿ. ತಕ್ಷಣ ಸಲಹೆಗಳನ್ನು ನೋಡಿ.",
    "App Language": "ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ",
    "Advanced Voice Speech Narration": "ಸುಧಾರಿತ ಧ್ವನಿ ವಿವರಣೆ",
    "Speaking Speed": "ಮಾತನಾಡುವ ವೇಗ",
    "Study Career Progression Path": "ಶೈಕ್ಷಣಿಕ ಪ್ರಗತಿ ಹಾದಿ",
    "Track your academic level and rank milestones": "ನಿಮ್ಮ ಶೈಕ್ಷಣಿಕ ಮಟ್ಟ ಮತ್ತು ಗುರಿಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
    "Your Current Level": "ಪ್ರಸ್ತುತ ಮಟ್ಟ",
    "Experience Points": "ಅನುಭವದ ಅಂಕಗಳು",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM ಕಲ್ಪನೆಗಳನ್ನು ಕರಗತ ಮಾಡಿಕೊಂಡು, ರಸಪ್ರಶ್ನೆಗಳನ್ನು ಎದುರಿಸಿ ಹಂತಗಳನ್ನು ಹೆಚ್ಚಿಸಿಕೊಳ್ಳಿ!",
    "Your Active Learning Progress": "ನಿಮ್ಮ ಸಕ್ರಿಯ ಕಲಿಕೆಯ ಪ್ರಗತಿ",
    "Recent Interactive Chat Sessions": "ಇತ್ತೀಚಿನ ಚಾಟ್ ಸೆಷನ್‌ಗಳು"
  },
  ml: {
    "home": "ഹോം",
    "search": "തിരച്ചിൽ",
    "history": "ചരിത്രം",
    "library": "ലൈബ്രറി",
    "profile": "പ്രൊഫൈൽ",
    "Good morning": "ശുഭോദയം",
    "Good afternoon": "ശുഭ മധ്യാഹ്നം",
    "Good evening": "ശുഭ സായാഹ്നം",
    "Streak": "സ്ട്രീക്ക്",
    "Concepts": "ആശയങ്ങൾ",
    "Quizzes": "ക്വിസ്സുകൾ",
    "Minutes": "മിനിറ്റുകൾ",
    Home: "ഹോം",
    StudyScan: "സ്റ്റഡി സ്കാൻ",
    "Saved Vault": "സേവ്ഡ് വോൾട്ട്",
    Timetable: "ടൈംടേബിൾ",
    "Profile Stats": "പ്രൊഫൈൽ സ്ഥിതിവിവരങ്ങൾ",
    Level: "ലെവൽ",
    XP: "എക്സ്പീരിയൻസ് പോയിന്റ്സ് (XP)",
    "weekly goal": "വാര ലക്ഷ്യം",
    "Choose Tutor Persona": "ട്യൂട്ടർ ശൈലി തിരഞ്ഞെടുക്കുക",
    "Ask AI Teacher": "AI ടീച്ചറോട് ചോദിക്കുക",
    "Practice STEM Quiz": "STEM ക്വിസ് പരിശീലിക്കുക",
    "Saved Concepts": "സേവ് ചെയ്ത ആശയങ്ങൾ",
    "Edit Profile": "പ്രൊഫൈൽ തിരുത്തുക",
    "Save Settings": "ക്രമീകരണങ്ങൾ സേവ് ചെയ്യുക",
    "Guest Explorer": "ഗസ്റ്റ് എക്സ്പ്ലോറർ",
    "Class 8": "ക്ലാസ് 8",
    "Class 9": "ക്ലാസ് 9",
    "Class 10": "ക്ലാസ് 10",
    "Class 11": "ക്ലാസ് 11",
    "Class 12": "ക്ലാസ് 12",
    "Undergrad": "ബിരുദം",
    "Principal Study Systems": "പ്രധാന പഠന സംവിധാനങ്ങൾ",
    "Start Fresh": "വീണ്ടും തുടങ്ങുക",
    "Instant voice/chat doubts solver & simulation explorer": "തൽക്ഷണ സംശയ നിവാരണവും സിമുലേഷനും",
    "Quick Quiz": "ദ്രുത ക്വിസ്",
    "Custom topic MCQ generator & diagnostic reward leveler": "വിഷയാധിഷ്ഠിത MCQ നിർമ്മാണവും ലെവലുകളും",
    "Voice Tutor": "വോയ്‌സ് ട്യൂട്ടർ",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "സംഗ്രഹങ്ങളും ഫ്ലാഷ് കാർഡുകളും കേൾക്കുക & സംസാരിക്കുക",
    "Scan Textbook": "പാഠപുസ്തകം സ്കാൻ ചെയ്യുക",
    "Click to launch the live camera instantly to analyze chapters": "ലൈവ് ക്യാമറ ഉപയോഗിച്ച് പാഠങ്ങൾ വിശകലനം ചെയ്യുക",
    "StudyScan Hub": "സ്റ്റഡിസ്കാൻ ഹബ്",
    "Your Offline Study Vault": "ഓഫ്‌ലൈൻ സ്റ്റഡി വോൾട്ട്",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "സേവ് ചെയ്ത വിവരങ്ങളെല്ലാം ഇവിടെ കാണാം. ഇന്റർനെറ്റ് ഇല്ലാതെ പഠിക്കുക!",
    "Search offline vault contents...": "ഓഫ്‌ലൈൻ വോൾട്ടിൽ തിരയുക...",
    "Study Planner Timetable": "സ്റ്റഡി പ്ലാനർ ടൈംടേബിൾ",
    "Manage your week": "പഠനവാരം ക്രമീകരിക്കുക",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "വിദ്യ നിങ്ങളുടെ പാഠങ്ങൾ വിശകലനം ചെയ്ത് 5 മികച്ച പഠനപദ്ധതികൾ തയ്യാറാക്കട്ടെ. താഴെ ക്ലിക്ക് ചെയ്യുക.",
    "App Language": "ആപ്പ് ഭാഷ",
    "Advanced Voice Speech Narration": "വോയ്‌സ് വിശദീകരണം",
    "Speaking Speed": "സംസാര വേഗത",
    "Study Career Progression Path": "പഠന പുരോഗതി വഴി",
    "Track your academic level and rank milestones": "നിങ്ങളുടെ പഠന ലെവലുകളും ലക്ഷ്യങ്ങളും ട്രാക്ക് ചെയ്യുക",
    "Your Current Level": "നിലവിലെ ലെവൽ",
    "Experience Points": "എക്സ്പീരിയൻസ് പോയിന്റുകൾ",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM ആശയങ്ങൾ പഠിച്ചും ക്വിസുകളിൽ പങ്കെടുത്തും ലെവലുകൾ ഉയർത്തുക!",
    "Your Active Learning Progress": "പഠന പുരോഗതി വിലയിరుത്തൽ",
    "Recent Interactive Chat Sessions": "അടുത്തകാലത്തെ ചാറ്റുകൾ"
  },
  bn: {
    "home": "হোম",
    "search": "অনুসন্ধান",
    "history": "ইতিহাস",
    "library": "লাইব্রেরি",
    "profile": "প্রোফাইল",
    "Good morning": "শুভ সকাল",
    "Good afternoon": "শুভ দুপুর",
    "Good evening": "শুভ সন্ধ্যা",
    "Streak": "স্ট্রিক",
    "Concepts": "ধারণা",
    "Quizzes": "কুইজ",
    "Minutes": "মিনিট",
    Home: "হোম",
    StudyScan: "স্টাডি স্ক্যান",
    "Saved Vault": "সংরক্ষিত ভল্ট",
    Timetable: "সময়সূচী",
    "Profile Stats": "প্রোফাইল পরিসংখ্যান",
    Level: "লেভেল",
    XP: "অভিজ্ঞতা পয়েন্ট (XP)",
    "weekly goal": "সাপ্তাহিক লক্ষ্য",
    "Choose Tutor Persona": "টিউটর স্টাইল বেছে নিন",
    "Ask AI Teacher": "AI শিক্ষককে জিজ্ঞাসা করুন",
    "Practice STEM Quiz": "STEM কুইজ অনুশীলন",
    "Saved Concepts": "সংরক্ষিত ধারণা",
    "Edit Profile": "প্রোফাইল পরিবর্তন",
    "Save Settings": "সেটিংস সংরক্ষণ করুন",
    "Guest Explorer": "অদ্বিথি অন্বেষক",
    "Class 8": "অষ্টম শ্রেণী",
    "Class 9": "নবম শ্রেণী",
    "Class 10": "দশম শ্রেণী",
    "Class 11": "একাদশ শ্রেণী",
    "Class 12": "দ্বাদশ শ্রেণী",
    "Undergrad": "স্নাতক",
    "Principal Study Systems": "প্রধান পাঠ্য পদ্ধতি",
    "Start Fresh": "নতুন করে শুরু করুন",
    "Instant voice/chat doubts solver & simulation explorer": "তাত্ক্ষণিক ভয়েস/চ্যাট সন্দেহ সমাধান এবং সিমুলেশন",
    "Quick Quiz": "দ্রুত কুইজ",
    "Custom topic MCQ generator & diagnostic reward leveler": "টপিক ভিত্তিক MCQ জেনারেটর এবং রিওয়ার্ড লেভেল",
    "Voice Tutor": "ভয়েস টিউটর",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "সারসংক্ষেপ, ফ্ল্যাশকার্ড এবং টিপস শুনুন ও বলুন",
    "Scan Textbook": "পাঠ্যবই স্ক্যান করুন",
    "Click to launch the live camera instantly to analyze chapters": "অধ্যায় বিশ্লেষণ করতে তাত্ক্ষণিক লাইভ ক্যামেরা চালু করুন",
    "StudyScan Hub": "স্টাডেস্ক্যান হাব",
    "Your Offline Study Vault": "অফলাইন স্টাডি ভল্ট",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "সংরक्षित সমস্ত নোট, ব্যাখ্যা এবং কুইজ ফলাফল এখানে পাবেন। ইন্টারনেট ছাড়াই পড়ুন!",
    "Search offline vault contents...": "অফলাইন ভল্ট সার্চ করুন...",
    "Study Planner Timetable": "স্টাডি প্ল্যানার সময়সূচী",
    "Manage your week": "আপনার সপ্তাহ পরিচালনা করুন",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "বিদ্যাকে আপনার পড়াশোনা বিশ্লেষণ করে ৫টি সেরা সাপ্তাহিক পরিকল্পনা তৈরি করতে দিন। নিচে ক্লিক করুন।",
    "App Language": "অ্যাপের ভাষা",
    "Advanced Voice Speech Narration": "উন্নত ভয়েস স্পিচ বর্ণনা",
    "Speaking Speed": "বলার গতি",
    "Study Career Progression Path": "শিক্ষা অগ্রগতির পথ",
    "Track your academic level and rank milestones": "আপনার একাডেমিক স্তর এবং লক্ষ্য ট্র্যাক করুন",
    "Your Current Level": "বর্তমান লেভেল",
    "Experience Points": "অভিজ্ঞতা পয়েন্ট",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM ধারণা আয়ত্ত করে, কুইজ খেলে লেভেল উন্নত করুন!",
    "Your Active Learning Progress": "আপনার সক্রিয় শেখার অগ্রগতি",
    "Recent Interactive Chat Sessions": "সাম্প্রতিক চ্যাট সেশন"
  },
  ur: {
    "home": "ہوم",
    "search": "تلاش",
    "history": "تاریخ",
    "library": "لائبریری",
    "profile": "پروفائل",
    "Good morning": "صبح بخیر",
    "Good afternoon": "دوپہر بخیر",
    "Good evening": "شام بخیر",
    "Streak": "سلسلہ",
    "Concepts": "خیالات",
    "Quizzes": "کوئز",
    "Minutes": "منٹ",
    Home: "ہوم",
    StudyScan: "اسٹڈی اسکین",
    "Saved Vault": "محفوظ شدہ والٹ",
    Timetable: "ٹائم ٹیبل",
    "Profile Stats": "پروفائل معلومات",
    Level: "لیول",
    XP: "پوائنٹس (XP)",
    "weekly goal": "ہفتہ وار ہدف",
    "Choose Tutor Persona": "ٹیوٹر کا انداز منتخب کریں",
    "Ask AI Teacher": "AI استاد سے پوچھیں",
    "Practice STEM Quiz": "STEM کوئز کی مشق کریں",
    "Saved Concepts": "محفوظ کردہ تصورات",
    "Edit Profile": "پروفائل تبدیل کریں",
    "Save Settings": "ترتیبات محفوظ کریں",
    "Guest Explorer": "مہمان طالب علم",
    "Class 8": "کلاس 8",
    "Class 9": "کلاس 9",
    "Class 10": "کلاس 10",
    "Class 11": "کلاس 11",
    "Class 12": "کلاس 12",
    "Undergrad": "گریجویٹ",
    "Principal Study Systems": "بنیادی تعلیمی نظام",
    "Start Fresh": "نیا آغاز کریں",
    "Instant voice/chat doubts solver & simulation explorer": "فوری آواز/چیٹ کے ذریعے شکوک و شبہات کا حل اور تشریح",
    "Quick Quiz": "فوری کوئز",
    "Custom topic MCQ generator & diagnostic reward leveler": "موضوعاتی سوالات اور انعامی درجات",
    "Voice Tutor": "وائس ٹیوٹر",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "خلاصہ، فلیش کارڈز اور تجاویز سنیں اور بات چیت کریں",
    "Scan Textbook": "کتاب اسکین کریں",
    "Click to launch the live camera instantly to analyze chapters": "ابواب کا تجزیہ کرنے کے لیے فوری لائیو کیمرہ چلائیں",
    "StudyScan Hub": "اسٹڈی اسکین ہب",
    "Your Offline Study Vault": "آپ کا آف لائن اسٹڈی والٹ",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "محفوظ کردہ تمام نوٹس اور کوئز کے نتائج یہاں ملیں گے۔ انٹرنیٹ کے بغیر پڑھیں!",
    "Search offline vault contents...": "آف لائن مواد تلاش کریں...",
    "Study Planner Timetable": "اسٹڈی پلانر ٹائم ٹیبل",
    "Manage your week": "اپنے ہفتے کا انتظام کریں",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "ودیا کو آپ کا مطالعہ دیکھ کر 5 بہترین ہفتہ وار تعلیمی منصوبے بنانے دیں۔ نیچے کلک کریں۔",
    "App Language": "ایپ کی زبان",
    "Advanced Voice Speech Narration": "جدید صوتی آواز کی ترسیل",
    "Speaking Speed": "بولنے کی رفتار",
    "Study Career Progression Path": "تعلیमी ترقی کا راستہ",
    "Track your academic level and rank milestones": "اپنے تعلیمی درجات اور اہداف کو ٹریک کریں",
    "Your Current Level": "موجودہ لیول",
    "Experience Points": "پوائنٹس",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "STEM تصورات سیکھ کر اور کوئز حل کر کے اپنے درجات بڑھائیں!",
    "Your Active Learning Progress": "آپ کی تعلیمی سرگرمی کی رپورٹ",
    "Recent Interactive Chat Sessions": "حالیہ تعلیمی گفتگو"
  },
  ar: {
    "home": "الرئيسية",
    "search": "بحث",
    "history": "السجل",
    "library": "المكتبة",
    "profile": "الملف الشخصي",
    "Good morning": "صباح الخير",
    "Good afternoon": "مساء الخير",
    "Good evening": "مساء الخير",
    "Streak": "التتابع",
    "Concepts": "المفاهيم",
    "Quizzes": "اختبارات",
    "Minutes": "دقائق",
    Home: "الرئيسية",
    StudyScan: "مسح الدراسة",
    "Saved Vault": "الخزنة المحفوظة",
    Timetable: "الجدول الدراسي",
    "Profile Stats": "الإحصائيات",
    Level: "المستوى",
    XP: "نقاط الخبرة (XP)",
    "weekly goal": "الهدف الأسبوعي",
    "Choose Tutor Persona": "اختر شخصية المعلم",
    "Ask AI Teacher": "اسأل معلم الذكاء الاصطناعي",
    "Practice STEM Quiz": "تدريب اختبار STEM",
    "Saved Concepts": "المفاهيم المحفوظة",
    "Edit Profile": "تعديل الملف الشخصي",
    "Save Settings": "حفظ الإعدادات",
    "Guest Explorer": "المستكشف الضيف",
    "Class 8": "الصف الثامن",
    "Class 9": "الصف التاسع",
    "Class 10": "الصف العاشر",
    "Class 11": "الصف الحادي عشر",
    "Class 12": "الصف الثاني عشر",
    "Undergrad": "جامعي",
    "Principal Study Systems": "أنظمة الدراسة الرئيسية",
    "Start Fresh": "البدء من جديد",
    "Instant voice/chat doubts solver & simulation explorer": "حل فوري للشكوك بالصوت والدردشة ومستكشف المحاكاة",
    "Quick Quiz": "اختبار سريع",
    "Custom topic MCQ generator & diagnostic reward leveler": "مولد أسئلة اختيار من متعدد مخصص ومستويات الجوائز",
    "Voice Tutor": "معلم الصوت",
    "Listen & talk to Mascot summaries, flashcards & fun tips": "الاستماع والتحدث إلى ملخصات التميمة والبطاقات التعليمية والنصائح الطريفة",
    "Scan Textbook": "مسح كتاب دراسي",
    "Click to launch the live camera instantly to analyze chapters": "انقر لتشغيل الكاميرا الحية فوراً لتحليل الفصول",
    "StudyScan Hub": "مركز مسح الدراسة",
    "Your Offline Study Vault": "خزنتك الدراسية دون اتصال بالإنترنت",
    "All saved concept notes, explanations, customized quiz results, whiteboard doodles, and voice recordings are archived locally here. Read and practice without internet!": "يتم أرشفة جميع الملاحظات والشروح ونتائج الاختبارات والرسوم المخططة هنا محلياً. اقرأ وتدرب دون إنترنت!",
    "Search offline vault contents...": "بحث محتويات الخزنة المحفوظة...",
    "Study Planner Timetable": "مخطط الجدول الدراسي",
    "Manage your week": "إدارة أسبوعك الدراسي",
    "Let VIDYA examine your lesson stats, class topics, and practice questions to frame 5 optimal weekly study plans. See suggestions instantly by clicking below.": "دع فيديا تفحص إحصاءات دروسك ومواضيع صفك لتصميم 5 خطط دراسية أسبوعية مثالية. شاهد المقترحات فوراً بالضغط أدناه.",
    "App Language": "لغة التطبيق",
    "Advanced Voice Speech Narration": "سرد صوتي متقدم والحديث",
    "Speaking Speed": "سرعة التحدث",
    "Study Career Progression Path": "مسار التقدم الوظيفي والدراسي",
    "Track your academic level and rank milestones": "تتبع مستواك الأكاديمي وإنجازاتك الدراسية",
    "Your Current Level": "مستواك الحالي",
    "Experience Points": "نقاط الخبرة",
    "Gain Level advancement status dynamically by mastering STEM concepts, challenging yourself in quick quizzes, and interacting with the AI teacher companion!": "احصل على ترقية لمستواك الدراسي عبر إتقان مفاهيم STEM، وتحدي نفسك في اختبارات سريعة، والتحدث لمعلم فيديا الذكي!",
    "Your Active Learning Progress": "تقدمك الدراسي النشط",
    "Recent Interactive Chat Sessions": "جلسات الدردشة التفاعلية الأخيرة"
  }
};

const LanguageContext = createContext<{
  locale: string;
  setLocale: (locale: string) => void;
  t: (key: TranslationKey) => string;
}>({
  locale: "en",
  setLocale: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocale] = useState(() => {
    if (typeof localStorage !== "undefined") {
      return localStorage.getItem("app_locale") || "en";
    }
    return "en";
  });

  const t = (key: TranslationKey) => {
    return translations[locale]?.[key] || translations["en"]?.[key] || key;
  };

  const handleSetLocale = (newLocale: string) => {
    setLocale(newLocale);
    localStorage.setItem("app_locale", newLocale);
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale: handleSetLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  const context = useContext(LanguageContext);
  return (key: TranslationKey) => {
    if (!context) return key;
    return context.t(key);
  };
}

export const LANGUAGE_NAMES_FOR_AI: Record<string, string> = {
  en: "English",
  te: "Telugu",
  hi: "Hindi",
  mr: "Marathi",
  ta: "Tamil",
  kn: "Kannada",
  ml: "Malayalam",
  bn: "Bengali",
  ur: "Urdu",
  ar: "Arabic"
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  return {
    language: context?.locale || "en",
    setLanguage: (lang: string) => {
      if (!context) return;
      let code = lang.toLowerCase();
      if (code.startsWith("eng") || code === "en") code = "en";
      else if (code.startsWith("hin") || code === "hi" || code === "हिंदी") code = "hi";
      else if (code.startsWith("tel") || code === "te" || code === "తెలుగు") code = "te";
      else if (code.startsWith("mar") || code === "mr" || code === "मराठी") code = "mr";
      else if (code.startsWith("tam") || code === "ta" || code === "தமிழ்") code = "ta";
      else if (code.startsWith("kan") || code === "kn" || code === "ಕನ್ನಡ") code = "kn";
      else if (code.startsWith("mal") || code === "ml" || code === "മലയാളം") code = "ml";
      else if (code.startsWith("ben") || code === "bn" || code === "বাংলা") code = "bn";
      else if (code.startsWith("urd") || code === "ur" || code === "اردو") code = "ur";
      else if (code.startsWith("ara") || code === "ar" || code === "العربية") code = "ar";
      
      context.setLocale(code);
    },
  };
}
